### ISSUE TITLE
从chat.openai.com复制的代码会带上不必要的语言类型和复制按钮文字

### ISSUE THREAD

**Issue by TonyYanOnFire** [icelam/code-copier#2]
从chat.openai.com复制的代码会带上这些不必要的内容
```
javascript
Copy code
...
```

原因应该是因为这些内容放到了pre标签下. 可以考虑增加域名的判断做特殊处理.

**Comment by icelam** [comment]
Try right-clicking on the code itself instead of the header of the code block. OpenAI has a nested `<pre>` and `<code>` in their code block UI, illustrated below: 

https://user-images.githubusercontent.com/6780420/225305432-1dc5447b-4185-4de8-aa05-3ad6124a4883.mov

![Illustration](https://user-images.githubusercontent.com/6780420/225308128-c5b56584-5f55-4a78-a568-c340a80bd023.png)

Since the `<pre>` tag is usually used for preformatted text according to [HTML Living Standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element), it's more reasonable to assume that the content wrapped inside is a code fragment - however, I'm working on a feature suggestion in issue #1 which may allow users to filter out unnecessary content.

**Comment by TonyYanOnFire** [comment]
确实, 复制的结果和鼠标点击位置有关, 在代码元素之外点击实际上触发的是pre元素的事件, 因此带上了header的内容. 我们可以在code元素上增加outline样式再观察, 如下图. 只有在outline包裹的地方进行复制, 结果才符合预期

![image](https://user-images.githubusercontent.com/55646026/225418578-4892da13-777f-4054-92e9-5553873331be.png)

看起来这个问题可以通过改变使用方式来解决, 插件本身无需改动.
